### ISSUE TITLE
(question) How do I visualize or use this to input video and output video? or as a start, input image and output image?

### ISSUE THREAD

**Issue by ZardashtKaya** [zhuker/ntsc#1]

**Comment by JargeZ** [comment]
Hi!
I used this algorithm and implemented an interface for convenience
https://github.com/JargeZ/ntsc#readme

You can try to use it and write your suggestions if you want :)

**Comment by ZardashtKaya** [comment]
@JargeZ  Your code didn't work, the problem is in this line: `from funcs import resize_to_height`
i think I need that module, could u please fix it?

**Comment by JargeZ** [comment]
@ZardashtKaya  Oh, I'm sorry.
I forgot to make a git add for this file. I'll fix it now
Thanks for saying

**Comment by ZardashtKaya** [comment]
that's okay i was just really confused I thought there was a module named funcs in pip but I couldn't find it

**Comment by ZardashtKaya** [comment]
thank you for the fix
